version: "3"

services:
  vruby:
    image: rjricardo/progvoice-ruby
    networks:
      - progvoice
  vpython:
    image: rjricardo/progvoice-python
    networks:
      - progvoice
  vnode:
    image: rjricardo/progvoice-node
    ports:
      - "8020:3000"
    environment:
      - PORT=3000
      - UTC_OFFSET=-6
      - RETHINKDB_HOST=vrdb
      - RETHINKDB_PORT=28015
      - PYTHON_SERVER_HOST=vpython
      - PYTHON_SERVER_PORT=5000
      - RUBY_SERVER_HOST=vruby
      - RUBY_SERVER_PORT=3000
    networks:
      - progvoice
  vrdb:
    image: rethinkdb
    networks:
      - progvoice

networks:
  progvoice:
    driver: bridge
